version: "3"
services:
  gluetun:
    image: docker.io/qmcgaw/gluetun:v3.38
    container_name: gluetun
    restart: unless-stopped
    privileged: true # TODO: Only needed for some nftables modules, see https://github.com/containers/podman/issues/15120 for proper solution
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /data/deployment/podman_configs/gluetun:/gluetun:Z
    environment:
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/custom.md
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/protonvpn.md
      # Remaining values should be auto filled with mounted volume info in the wg0.conf
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
    ports:
      - 8112:8112 # deluge web UI
      - 6881:6881
      - 6881:6881/udp # deluge daemon download ports
      - 58846:58846 # deluge GTK UI
    deploy:
      resources:
        limits: # TODO: How much RAM do I actually need just for a VPN client?
          memory: 256M

  deluge:
    image: docker.io/linuxserver/deluge:latest # TODO: Switch to specific version tag, for some reason it failed to find manifest when i tried?
    container_name: deluge
    restart: unless-stopped
    environment:
      - PUID=1000 # TODO: Switch to 'deluge' user/group ID from my user ID, assign /data/torrents and /data/podman_configs/deluge permissions to deluge container/user
      - PGID=1000
      - TZ=America/Los_Angeles
      - DELUGE_LOGLEVEL=info
    volumes:
      - /data/deployment/podman_configs/deluge/:/config:Z
      - /data/torrents/:/downloads:Z # Note that the container expects a '/downloads' directory, mount as '/torrents' and things silently fail
    depends_on:
    - gluetun
    network_mode: "container:gluetun"
    deploy:
      resources:
        limits:
          memory: 2G
