---
- name: Configure Host
  hosts: all

  vars_files:
    - config.ansible.yml

  pre_tasks:
    - name: Install dnf packages for nas
      become_user: root
      become: true
      ansible.builtin.dnf:
        name:
          # first two are just for seboolean module
          # long term, figure out how to not require changing those host booleans
          # so gluetun can run truly rootless
          - python3-libselinux = 3.5
          - python3-libsemanage = 3.5
          - podman = 5:4.9.4
          - cockpit-podman = 87
          # This one contains machinectl, mostly for my own debugging
          - systemd-container = 254.10
        state: present

  tasks:
    # One requirement is a /data drive is mounted, I guess I have to do that on OS installation?
    # Find disks and create volumes/etc and mount based on UUID?
    - name: Create group for managing common data directory
      become: true
      become_user: root
      ansible.builtin.group:
        name: data
        system: true
        state: present

    - name: Make data dir accessible to all data users
      become: true
      become_user: root
      ansible.builtin.file:
        path: "/data" # TODO put into some config file?
        group: data
        mode: g=rwX,u=rwX,o-rwx
        recurse: true
        setype: container_file_t
        # TODO: Do i want this to be true? Seems like way to shoot myself in the foot
        # If I setup *arr suite of apps I may need to make this true
        follow: false

    - name: Core logic to create all users and containers
      ansible.builtin.include_tasks: tasks/users.ansible.yml
      loop:
        - torrents
      loop_control:
        loop_var: username
