---
- name: Configure Host
  hosts: all

  vars_files:
    # Use this instead of the hardcoding I'm doing
    - config.ansible.yml

  pre_tasks:
    - name: Install dnf packages for nas
      become_user: root
      become: true
      ansible.builtin.dnf:
        name:
          # first two are just for seboolean module
          # long term, figure out how to not require changing those host booleans
          # so gluetun can run truly rootless
          - python3-libselinux
          - python3-libsemanage
          # This is obviously required to make everything work
          - podman
          # This is the webui plugin, just for personal usage
          - cockpit-podman
          # This one contains machinectl, mostly for my own debugging
          - systemd-container
          # For host backup and restore
          - restic
           # fedora repos have old rclone version, run rclone selfupdate after install for v1.66.0+ with protondrive
           # requires I run rclone config after to add proton backend, can this be scripted with a config and auth file?
          - rclone
        state: present

  tasks:
    - name: Core logic to init the file system and mounts
      ansible.builtin.include_tasks: tasks/filesys.ansible.yml

    - name: Core logic to create all users and containers
      ansible.builtin.include_tasks: tasks/users.ansible.yml
      loop:
        - torrents
      loop_control:
        loop_var: username
