---
- name: Configure Host
  hosts: all

  vars_files:
    # Use this instead of the hardcoding I'm doing
    - config.ansible.yml

  vars_prompt:
    - name: raw_proton_code
      prompt: Enter the proton 2fa

  pre_tasks:
    - name: Install dnf packages for nas
      become_user: root
      become: true
      ansible.builtin.dnf:
        name:
          # first two are just for seboolean module
          # long term, figure out how to not require changing those host booleans
          # so gluetun can run truly rootless
          - python3-libselinux
          - python3-libsemanage
          # This is obviously required to make everything work
          - podman
          # This is the webui plugin, just for personal usage
          - cockpit-podman
          # This one contains machinectl, mostly for my own debugging
          - systemd-container
        state: present

  tasks:
    - name: Setup data volume
      ansible.builtin.include_tasks: tasks/filesys.ansible.yml

    - name: Core logic to create all users and containers
      ansible.builtin.include_tasks: tasks/users.ansible.yml
      loop: "{{ users }}"
      loop_control:
        loop_var: username
