---
- name: Configure Host
  hosts: all

  vars_files:
    - config.ansible.yml

  pre_tasks:
    - name: Install dnf packages for nas
      become_user: root
      become: true
      ansible.builtin.dnf:
        name:
          # first two are just for seboolean module
          # long term, figure out how to not require changing those host booleans
          # so gluetun can run truly rootless
          - python3-libselinux = 3.5
          - python3-libsemanage = 3.5
          - podman = 5:4.9.4
          - cockpit-podman = 87
          # This one contains machinectl, mostly for my own debugging
          - systemd-container = 254.10
        state: present

  tasks:
    # TODO: Maybe put this all in a dedicated zone,
    # and then I can just recreate the zone to recreate all firewall rules easily?
    # Maybe 1 zone per user account or 1 zone per container?
    - name: Open host firewall ports
      become: true
      become_user: root
      ansible.posix.firewalld:
        service: "{{ item }}"
        immediate: true
        permanent: true
        state: enabled
      loop:
        # ssh and dhcp should be auto configured by server installer, here for completeness
        - ssh
        - dhcpv6-client
        # cockpit web UI is optional but I want it here
        - cockpit
        # These are for gluetun/deluge, move to some config or users/torrents.ansible.yml file
        - deluge-web
        - deluge-daemon
        - deluge-thin-client-gtk

    # One requirement is a /data drive is mounted, I guess I have to do that on OS installation?
    # Find disks and create volumes/etc and mount based on UUID?
    - name: Create group for managing common data directory
      become: true
      become_user: root
      ansible.builtin.group:
        name: data
        system: true
        state: present

    - name: Make data dir accessible to all data users
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ data_dir }}" # TODO put into some config file?
        group: data
        mode: g=rwX,u=rwX,o-rwx
        recurse: true
        setype: container_file_t
        # TODO: Do i want this to be true? Seems like way to shoot myself in the foot
        # If I setup *arr suite of apps I may need to make this true
        follow: false

    - name: Core logic to create all users and containers
      ansible.builtin.include_tasks: tasks/users.ansible.yml
      loop: "{{ secret_files_by_username | map(attribute='username') }}"
      loop_control:
        loop_var: username
