---
- name: Configure Host
  hosts: all

  vars_files:
  - config.ansible.yml

  pre_tasks:
  - name: Install dnf packages for host
    become_user: root
    become: true
    ansible.builtin.dnf:
      name: 
      - podman
      - cockpit-podman 
      - python3-policycoreutils 
      - policycoreutils-python-utils 
      - python3-libselinux
      state: latest      

  tasks:
  - name: Core logic to create all users and containers
    ansible.builtin.include_tasks: users.ansible.yml
    loop: "{{ users }}"
    loop_control:
      loop_var: username

  - name: Open firewall ports
    become: true
    become_user: root
    ansible.posix.firewalld:
      immediate: true
      permanent: true
      port: "{{ item }}"
      state: enabled
    loop:
    # This are all for deluge/gluetun currently, move into the config yml?
    - 56881-56889/tcp
    - 56881-56889/udp
    - 8112/udp
    - 8112/tcp
    - 58856/tcp
    - 58856/udp

  # One requirement is a /data drive is mounted, I guess I have to do that on OS installation?
  # Find disks and create volumes/etc and mount based on UUID?
  - name: Create group for managing common data directory
    become: true
    become_user: root
    ansible.builtin.group:
      name: data
      system: true

  - name: Assign users to additonal groups
    become: true
    become_user: root
    ansible.builtin.user:
      name: "{{ item.key }}"
      groups: "{{ item.value }}"
      append: true
    loop: "{{ extra_group_members | dict2items }}"
    loop_control:
      label: "{{ item.key }}"

  - name: Make data dir accessible to all data users
    become: true
    become_user: true
    ansible.builtin.file:
      path: "{{ data_dir }}" # TODO put into some config file?
      group: data
      mode: g=rw,u=rw # TODO: Best perms? bear in mind torrents group writes to /data/torrents, restic reads from all, *arr read and write from specific paths
      recurse: true

  # These two are needed by gluetun container, the former
  # to access the /dev/net/tun device and the latter so the container
  # may load/read firewall rules with nftables module
  - name: Allow container to use host devices (viz. gluetun)
    ansible.posix.seboolean:
      name: container_use_devices
      state: true
      persistent: true

  - name: Allow container to load host kernel modules (viz. gluetun)
    ansible.posix.seboolean:
      name: domain_kernel_load_modules
      state: true
      persistent: true

  - name: Set SELinux fcontext customizations for allowing containers to read/write from /data dir
    community.general.sefcontext:
      target: '{{ data_dir }}(/.*)?'
      setype: container_file_t 
      state: present
