---
- name: Configure Host
  hosts: all

  vars_files:
    - config.ansible.yml

  pre_tasks:
    - name: Install dnf packages for nas
      become_user: root
      become: true
      ansible.builtin.dnf:
        name:
          # first two are just for seboolean module
          # long term, figure out how to not require changing those host booleans
          # so gluetun can run truly rootless
          - python3-libselinux = 3.5
          - python3-libsemanage = 3.5
          - podman = 5:4.9.4
          - cockpit-podman = 87
          # This one contains machinectl, mostly for my own debugging
          - systemd-container = 254.10
        state: present

  tasks:
    - name: Core logic to init the file system and mounts
      ansible.builtin.incldue_tasks: tasks/filesys.ansible.yml

    - name: Core logic to create all users and containers
      ansible.builtin.include_tasks: tasks/users.ansible.yml
      loop:
        - torrents
      loop_control:
        loop_var: username
