---
# Delete all users and try again
# Does not touch system wide settings like opened firewall ports,
# btrfs/filesys settings, and selinux perms. Just deletes the users
# Hopefully I can

- name: Delete container and user details from target node
  hosts: all

  vars_files:
    - config.ansible.yml

  tasks:
    - name: Delete the user accounts
      loop: "{{ users }}"
      loop_control:
        loop_var: username
      ansible.builtin.include_tasks:
        file: tasks/userdel.ansible.yml

    # TODO: Get this list from config.ansible.yml or $username.ansible.yml instead of hardcoding
    - name: Remove opened firewall ports
      become: true
      become_user: root
      ansible.posix.firewalld:
        port: "{{ item }}"
        immediate: true
        permanent: true
        state: disabled
      loop:
        - 8112/tcp
        - 6881/tcp
        - 6881/udp
        - 58846/tcp

    - name: Disallow container to use host devices (viz. gluetun)
      become: true
      become_user: root
      ansible.posix.seboolean:
        name: container_use_devices
        state: false
        persistent: true

    - name: Disallow container to load host kernel modules (viz. gluetun)
      become: true
      become_user: root
      ansible.posix.seboolean:
        name: domain_kernel_load_modules
        state: false
        persistent: true

    - name: "Reset selinux details on {{ data_dir }}"
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ data_dir }}"
        setype: default_t
        recurse: true
        follow: false
