---
# ansible.builtin.user would be better but that module does not support -F/--add-subids-for-system
- name: Create "{{ username }}" user
  ansible.builtin.command:
    creates: "/home/{{ username }}" # This works as long as we use standard home paths
    argv:
      - useradd
      - --create-home
      - --system
      - --add-subids-for-system
      - --user-group
      - "{{ username }}"

# Do I even need this if I place quadlets in /etc/?
- name: Set "{{ username }}" user to linger on login
  register: linger_result
  changed_when: linger_result.stdout != "AlreadyLingering"
  ansible.builtin.shell:
    cmd: "(loginctl show-user {{ username }} --no-pager --property=Linger --value --no-ask-password | grep yes) && echo AlreadyLingering || loginctl enable-linger {{ username }} --no-ask-password --no-pager"
    executable: /bin/bash

- name: Copy over quadlets
  environment:
    # This is set scoped to this task just for the validate block to work
    QUADLET_UNIT_DIRS: "/home/{{ username }}/.config/containers/systemd/"
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.config/containers/systemd/"
    mode: u=r,g=r
    src: "files/{{ username }}/"
    group: "{{ username }}"
    owner: "{{ username }}"
    validate: /usr/lib/systemd/system-generators/podman-system-generator --user --dryrun

- name: Copy any secret files, target paths and names specified in config.ansible.yml
  ansible.builtin.copy:
    dest: "/home/{{ username }}/{{ item.key }}"
    mode: u=r # TODO: Only secret used here is gluetun config which is readonly, in future some secret files may need read/write based on application
    content: "{{ item.value }}"
    group: "{{ username }}"
    owner: "{{ username }}"
  loop: "{{ query('ansible.builtin.subelements', secret_files_by_username, username, {'skip_missing': true }) }}"

# TODO: Ensure user started now and check that login is a success, container is up and stays up, etc
# If the container/user started earlier and stuff like file perms/selinux weren't yet set, we'll have issues