---

# This user only exists ATM to run a backup and sync on the /data dir


# Download and configure the bitwarden CLI program
# This only exists to pull secrets on user creation/setup that
# require refreshes like TOTP 2fa. In all other cases, prefer
# one time secrets setup on deployment within ansible with ansible-vault
# or the ansible-bitwarden plugin. I may not need TOTP 2fa refreshes,
# so disabling this for now. Will try just initial setup for rclone

# - name: Get the bw cli program
#   become: true
#   become_user: "{{ username }}"
#   ansible.builtin.get_url:
#     url: https://vault.bitwarden.com/download/?app=cli&platform=linux
#     dest: "~/.local/bin/bw"
#     mode: '500'
#     decompress: true
#     group: "{{ username }}"
#     owner: "{{ username }}"

# - name: Setup bw CLI
#   become: true
#   become_user: "{{ username }}"
#   register: bw_cli_login_result
#   environment:
#     # TODO: Set these env vars on ansible-deploy for automated auth
#     BW_CLIENTID:
#     BW_CLIENTSECRET:
#   ansible.builtin.command:
#     cmd: "bw --nointeraction --raw login"
#     creates: "~/.config/Bitwarden CLI/data.json"

# TODO: Initialize the target repos if they do not exist

- name: Create proton backend for data
  ansible.builtin.include_tasks: rclone_init.ansible.yml

- name: Generate script for data backup
  become: true
  become_user: root
  ansible.builtin.copy:
    dest: "~/backup.sh"
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: '500'
    validate: bash -n %s
    content: |
      #!/usr/bin/bash
      set -euo pipefail
      export HISTCONTROL=ignorespace

      # Leading space matters here
       export RESTIC_REPOSITORY_FILE=secrets/.restic_repo_data
       export RESTIC_PASSWORD_FILE=secrets/.restic_passwd_data

      if ! restic check; then
          printf "Pre backup check failed\n"
          exit 31
      fi

      restic backup {{ data_dir }} -vvv

      if ! restic check; then
          printf "Post backup check failed\n"
          exit 63
      fi

      restic forget --keep-daily 7 --keep-hourly 7 --keep-weekly 7 --prune

      if ! restic check; then
          printf "Post prune check failed\n"
          exit 127
      fi

- name: Generate script for data sync
  become: true
  become_user: root
  ansible.builtin.copy:
    dest: "~/sync.sh"
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: '500'
    validate: bash -n %s
    content: |
      #!/usr/bin/bash
      set -euo pipefail
      export HISTCONTROL=ignorespace

      # copy does not propogate deletes from local to remote, sync does
      # bisync is experimental and propogates deletes from remote to local
      # copy for now while testing, consider sync if I start to accumulate garbage
      rclone copy {{ backup_remote_name }}:nas-data -vv
