---

# One requirement is a /data drive is mounted, I guess I have to do that on OS installation?
# Find disks and create volumes/etc and mount based on UUID from a config.yml?
- name: Create group for managing common data directory
  become: true
  become_user: root
  ansible.builtin.group:
    name: data
    system: true
    state: present

- name: Make data dir accessible to all data users
  become: true
  become_user: root
  ansible.builtin.file:
    path: "/data" # TODO put into some config file?
    group: data
    mode: '770'
    recurse: true
    setype: container_file_t
    # TODO: Do i want this to be true? Seems like way to shoot myself in the foot
    # If I setup *arr suite of apps I may need to make this true
    follow: false

- name: Create systemd timer for btrfs scrub
  become: true
  become_user: root
  ansible.builtin.copy:
    group: root
    owner: root
    dest: /etc/systemd/system/btrfs-scrub.timer
    mode: '777'
    content: |
      [Unit]
      Description=Monthly scrub btrfs filesystem, verify block checksums
      Documentation=man:btrfs-scrub

      [Timer]
      # first saturday each month
      OnCalendar=Sat *-*-1..7 3:00:00
      RandomizedDelaySec=10min

      [Install]
      WantedBy=timers.target

- name: Create systemd service for btrfs scrub
  become: true
  become_user: root
  ansible.builtin.copy:
    group: root
    owner: root
    mode: '777'
    dest:  /etc/systemd/system/btrfs-scrub.service
    content: |
      [Unit]
      Description=Scrub btrfs filesystem, verify block checksums
      Documentation=man:btrfs-scrub

      [Service]
      Type=simple
      ExecStart=/bin/btrfs scrub start -Bd /data
      KillSignal=SIGINT
      IOSchedulingClass=idle
      CPUSchedulingPolicy=idle

- name: Enable systemd timer for btrfs scrub
  become: true
  become_user: root
  ansible.builtin.systemd_service:
    name: btrfs-scrub.timer
    state: started
    enabled: true
    scope: system
