---
# Note: For some reason u=rX on some mode args would result in files created with u=g=o=rX
# UMASK seems like it's not the issue, and I dislike the 0765 syntax for file modes, so I use o-rwx
# syntax explicitly to clear other file perms.

# ansible.builtin.user would be better instead of ansible.builtin.command:
# but that module does not support -F/--add-subids-for-system.
# And useradd does not allows specifying --add-subgids on creation, so we a few different
# command steps to create the user account

- name: "Create user {{ username }}"
  become: true
  become_user: root
  ansible.builtin.command:
    creates: "/home/{{ username }}"
    cmd: "useradd --create-home --system --add-subids-for-system --user-group --key UMASK=077 {{ username }}"

- name: Arrange quadlets, config, state and secrets
  ansible.builtin.include_tasks: "{{ username }}.ansible.yml"

- name: Set user to linger on login
  become: true
  become_user: root
  ansible.builtin.command:
    creates: "/home/{{ username }}"
    cmd: "loginctl enable-linger {{ username }} --no-ask-password --no-pager"

# TODO: Ensure user started now and check that login is a success, container is up and stays up, etc
# If the container/user started earlier and stuff like file perms/selinux weren't yet set, we'll have issues
