---

- name: Disable linger on user so I can kill them safely
  become: true
  become_user: root
  register: disable_linger_result
  failed_when:
    - "'Failed to look up user' not in disable_linger_result.stderr"
    - disable_linger_result.rc != 0
  ansible.builtin.command:
    cmd: "loginctl disable-linger {{ username }}"
    removes: "{{ data_dir }}/home/{{ username }}"

- name: Kill active user sessions
  become: true
  become_user: root
  register: pkill_result
  # 0 success, 1 means no processes matched
  failed_when: "pkill_result.rc > 1"
  ansible.builtin.command:
    cmd: "pkill -U {{ username }}"
    removes: "{{ data_dir }}/home/{{ username }}"

- name: Remove all users
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ username }}"
    state: absent
    remove: true

